---
# base on https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
language: python
python: "2.7"

before_install:
  # Updating apt cache repository
  - "sudo apt-get update -qq"

install:
  - "sudo pip install ansible"

script:
  # Run some test commands