---
  - name: Update apt package manager cache
    apt:  update_cache=yes cache_valid_time=3600

  - name: Installation of common packages
    apt:  name={{ item }} state=present
    with_items:
      - "{{ common_packages }}"